version: '3.8'

services:
  api-gateway:
    build:
      context: ./gateway
    container_name: nortear-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # - AUTH_SERVICE_URL=http://auth-service:8081
      # - CHAT_SERVICE_URL=http://chat-service:8082
      - MCP_SERVICE_URL=http://mcp-server:3000
    networks:
      - nortear-network
    restart: unless-stopped
    depends_on:
      - mcp-server 

  postgres-db:
    image: ankane/pgvector:latest
    profiles:
      - "infra"
    container_name: nortear-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - nortear-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  mcp-server:
    build:
      context: ./server-mcp 
    container_name: nortear-mcp
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - nortear-network
    restart: unless-stopped
    
networks:
  nortear-network:
    driver: bridge
    
volumes:
  pgdata:
