CREATE TABLE user
(
    id       LONG         NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
    nome     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
)

CREATE TABLE skill
(
    id   LONG         NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
    nome VARCHAR(255) NOT NULL,
)

CREATE TABLE user_skill
(
    user_id LONG NOT NULL,
    skill_id LONG NOT NULL,

    CONSTRAINT fk_user FOREIGN KEY (user_id) references user(id),
    CONSTRAINT fk_skill FOREIGN KEY (skill_id) references skill(id);
)

